language: cpp

jobs:
  include:
    - os: windows
      arch: amd64
      env: OS=windows
    - os: linux
      arch: x64
      env: OS=x64_linux
branches:
  only:
    - master

script:
    - mkdir builds
    - cd builds
    - cmake -D ubuntu=1 ..
    - cmake --build . --config release
